# Imagen base que ya trae Kafka (con KRaft, sin ZooKeeper)
FROM bitnami/kafka:3.7

# (Opcional) Pon defaults de entorno aquí, aunque normalmente se pasan desde compose
# ENV KAFKA_ENABLE_KRAFT=yes
# ENV KAFKA_CFG_NODE_ID=1

# (Opcional) Copiar config propia si quieres personalizar server.properties
# COPY server.properties /opt/bitnami/kafka/config/server.properties

# El ENTRYPOINT y CMD los maneja la imagen base de Bitnami
